[package]
name = "tree-sitter-languages"
version = "0.1.0"
authors = ["Andy Russell <arussell123@gmail.com>"]
edition = "2018"

[lib]
doctest = false

[dependencies]
tree-sitter = "0.16.1"

[build-dependencies]
cc = "1.0.54"
quote = "1.0.7"
